### ISSUE TITLE
This is already persisted - why the TODO? 

### ISSUE THREAD

**Issue by krrishdholakia** [fastrepl/proxy#8]
https://github.com/fastrepl/proxy/blob/b937d5b32084b7aa8638bd6edbcdcc027126a41b/proxy/main.py#L18

Hi @yujonglee, 

I saw the `#TODO: Should persist`, isn't this already being persisted by the hosted budget manager implementation?

**Comment by yujonglee** [comment]
Yeah we should remove the todo. My bad.

**Comment by yujonglee** [comment]
@krrishdholakia 

This should be fixed now. https://github.com/fastrepl/proxy/blob/ded65bd79efdcdfe3542e34abf4bc59cd6b53cf3/proxy/main.py#L15
